name: GCM_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py39h6e9494a_1
  - argon2-cffi=20.1.0=py39hcbf5805_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=3.3.0=pyh44b312d_0
  - ca-certificates=2021.5.30=h033912b_0
  - certifi=2021.5.30=py39h6e9494a_0
  - cffi=1.14.5=py39h319c39b_0
  - cycler=0.10.0=py_2
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h4cff582_1
  - igl=2.2.1=py39h579f354_1
  - importlib-metadata=4.5.0=py39h6e9494a_0
  - ipydatawidgets=4.2.0=pyhd3deb0d_0
  - ipykernel=5.5.5=py39h71a6800_0
  - ipython=7.24.1=py39h71a6800_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jbig=2.1=h0d85af4_2003
  - jedi=0.18.0=py39h6e9494a_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jpeg=9d=hbcb3906_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py39h6e9494a_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - kiwisolver=1.3.1=py39hedf5dff_1
  - lcms2=2.12=h577c468_0
  - lerc=2.2.1=h046ec9c_0
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libcxx=11.1.0=habf9029_0
  - libdeflate=1.7=h35c211d_5
  - libffi=3.3=hb1e8313_2
  - libgfortran=5.0.0=9_3_0_h6c81a4c_22
  - libgfortran5=9.3.0=h6c81a4c_22
  - liblapack=3.9.0=9_openblas
  - libopenblas=0.3.15=openmp_h5e1b9a4_1
  - libpng=1.6.37=h7cec526_2
  - libsodium=1.0.18=hbcb3906_1
  - libtiff=4.3.0=h1167814_1
  - libwebp-base=1.2.0=h0d85af4_2
  - llvm-openmp=11.1.0=hda6cdc1_1
  - lz4-c=1.9.3=h046ec9c_0
  - markupsafe=2.0.1=py39h89e85a6_0
  - matplotlib-base=3.4.2=py39hb07454d_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - meshplot=0.4.0=pyhd3deb0d_2
  - mistune=0.8.4=py39hcbf5805_1003
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py39h6e9494a_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.4.0=pyha770c72_0
  - numpy=1.20.3=py39h7eed0ac_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1k=h0d85af4_0
  - packaging=20.9=pyh44b312d_0
  - pandoc=2.14.0.1=h0d85af4_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.2.0=py39h5fdd921_1
  - pip=21.1.1=py39hecd8cb5_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py39hcbf5805_2
  - python=3.9.5=h88f2d9e_3
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pythreejs=2.3.0=pyhd8ed1ab_0
  - pyzmq=22.1.0=py39h7fec2f1_0
  - readline=8.1=h9ed2024_0
  - scipy=1.6.3=py39h056f1c0_0
  - send2trash=1.5.0=py_0
  - setuptools=52.0.0=py39hecd8cb5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.35.4=hce871da_0
  - terminado=0.10.0=py39h6e9494a_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py39hcbf5805_1
  - traitlets=5.0.5=py_0
  - traittypes=0.2.1=pyh9f0ad1d_2
  - tzdata=2020f=h52ac0ba_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py39h6e9494a_4
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=h1c7c35f_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.5.0=h582d3a0_0
prefix: /Users/qbecker/opt/anaconda3/envs/GCM_env
